apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seamline-api
  namespace: seamline
  labels:
    app: seamline-api
    {{- include "seamline.labels" . | nindent 4 }}
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.ingress.apiHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seamline-api
                port:
                  number: 8080
