apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: seamline-observability
  labels:
    app: grafana
    {{- include "seamline.labels" . | nindent 4 }}
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.ingress.grafanaHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
