apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: seamline-observability
  labels:
    app: grafana
    {{- include "seamline.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: grafana
