apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: seamline-observability
  labels:
    app: kube-state-metrics
    {{- include "seamline.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: kube-state-metrics
