apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: seamline-observability
  labels:
    {{- include "seamline.labels" . | nindent 4 }}
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    exporters:
      otlp/jaeger:
        endpoint: jaeger.seamline-observability.svc:4317
        tls:
          insecure: true
      prometheus:
        endpoint: 0.0.0.0:8889

    processors:
      batch:
        timeout: 5s

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/jaeger]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
