apiVersion: v1
kind: Service
metadata:
  name: seamline-rabbitmq
  namespace: seamline
  labels:
    app: seamline-rabbitmq
    {{- include "seamline.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  selector:
    app: seamline-rabbitmq
