// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Seamline.Modules.Risk.Internal;

#nullable disable

namespace Seamline.Modules.Risk.Internal.Migrations
{
    [DbContext(typeof(RiskDbContext))]
    [Migration("20260727212755_AddWeightedAvgPriceAndValuationSnapshot")]
    partial class AddWeightedAvgPriceAndValuationSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("risk")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Seamline.Modules.Risk.Internal.CreditReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CounterpartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("counterparty_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("uuid")
                        .HasColumnName("trade_id");

                    b.HasKey("Id");

                    b.HasIndex("TradeId");

                    b.ToTable("credit_reservation", "risk");
                });

            modelBuilder.Entity("Seamline.Modules.Risk.Internal.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommodityCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("commodity_code");

                    b.Property<string>("DeliveryPeriod")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("delivery_period");

                    b.Property<decimal>("NetVolume")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("net_volume");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("WeightedAvgPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("weighted_avg_price");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CommodityCode", "DeliveryPeriod")
                        .IsUnique();

                    b.ToTable("position", "risk");
                });

            modelBuilder.Entity("Seamline.Modules.Risk.Internal.ValuationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommodityCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("commodity_code");

                    b.Property<decimal>("CurvePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("curve_price");

                    b.Property<DateTimeOffset>("CurvePublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("curve_published_at");

                    b.Property<string>("DeliveryPeriod")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("delivery_period");

                    b.Property<decimal>("MtmAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("mtm_amount");

                    b.Property<decimal>("NetVolume")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("net_volume");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("ValuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valued_at");

                    b.Property<decimal>("WeightedAvgPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("weighted_avg_price");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CommodityCode", "DeliveryPeriod", "ValuedAt");

                    b.ToTable("valuation_snapshot", "risk");
                });
#pragma warning restore 612, 618
        }
    }
}
